import type { GameRegistryItem } from '@/features/games/types';

export const GAME_REGISTRY: GameRegistryItem[] = [
  {
    id: 'farki-bul',
    title: 'Farki Bul',
    category: 'attention',
    durationSeconds: 180,
    description: 'Secici dikkat oyunu. Grid uzerinde digerlerinden farkli kutuyu bul.',
    migrated: true,
  },
  {
    id: 'kelime-avi',
    title: 'Kelime Avi',
    category: 'language',
    durationSeconds: 150,
    description: 'Hedef harf veya heceyi iceren kartlari bulma oyunu.',
    migrated: true,
  },
  {
    id: 'attention-coding',
    title: 'Dikkat ve Kodlama',
    category: 'attention',
    durationSeconds: 180,
    description: 'Numara-sekil kod tablosuna gore hizli eslestirme oyunu.',
    migrated: true,
  },
  {
    id: 'dikkat-ve-kodlama',
    title: 'Dikkat ve Kodlama',
    category: 'attention',
    durationSeconds: 180,
    description: 'Numara-sekil kod tablosuna gore hizli eslestirme oyunu.',
    migrated: true,
  },
  {
    id: 'sembol-arama',
    title: 'Sembol Arama',
    category: 'attention',
    durationSeconds: 180,
    description: 'Hedef sembolun kac kez gectigini hizli bulma oyunu.',
    migrated: true,
  },
  {
    id: 'symbol-search',
    title: 'Sembol Arama',
    category: 'attention',
    durationSeconds: 180,
    description: 'Hedef sembolun kac kez gectigini hizli bulma oyunu.',
    migrated: true,
  },
  {
    id: 'sekil-hafizasi',
    title: 'Sekil Hafizasi',
    category: 'memory',
    durationSeconds: 180,
    description: 'Sekil-renk eslesmelerini ezberleyip sorulari cevaplama oyunu.',
    migrated: true,
  },
  {
    id: 'symbol-match',
    title: 'Sekil Hafizasi',
    category: 'memory',
    durationSeconds: 180,
    description: 'Sekil-renk eslesmelerini ezberleyip sorulari cevaplama oyunu.',
    migrated: true,
  },
  {
    id: 'gorsel-tarama',
    title: 'Gorsel Tarama',
    category: 'attention',
    durationSeconds: 180,
    description: 'Gridde hedef sembolu hizli tarayip secme oyunu.',
    migrated: true,
  },
  {
    id: 'visual-scanning',
    title: 'Gorsel Tarama',
    category: 'attention',
    durationSeconds: 180,
    description: 'Gridde hedef sembolu hizli tarayip secme oyunu.',
    migrated: true,
  },
  {
    id: 'isitsel-hafiza',
    title: 'Isitsel Hafiza',
    category: 'memory',
    durationSeconds: 180,
    description: 'Ses dizilerini dinleyip ayni sirayla tekrar etme oyunu.',
    migrated: true,
  },
  {
    id: 'auditory-memory',
    title: 'Isitsel Hafiza',
    category: 'memory',
    durationSeconds: 180,
    description: 'Ses dizilerini dinleyip ayni sirayla tekrar etme oyunu.',
    migrated: true,
  },
  {
    id: 'tepki-suresi',
    title: 'Tepki Suresi',
    category: 'attention',
    durationSeconds: 180,
    description: 'Sinyale dogru zamanda tepki verme ve erken tiklamayi engelleme oyunu.',
    migrated: true,
  },
  {
    id: 'reaction-time',
    title: 'Tepki Suresi',
    category: 'attention',
    durationSeconds: 180,
    description: 'Sinyale dogru zamanda tepki verme ve erken tiklamayi engelleme oyunu.',
    migrated: true,
  },
  {
    id: 'sozel-analoji',
    title: 'Sozel Analoji',
    category: 'language',
    durationSeconds: 180,
    description: 'Kelime iliskilerini cozup dogru analoji tamamlama oyunu.',
    migrated: true,
  },
  {
    id: 'verbal-analogy',
    title: 'Sozel Analoji',
    category: 'language',
    durationSeconds: 180,
    description: 'Kelime iliskilerini cozup dogru analoji tamamlama oyunu.',
    migrated: true,
  },
  {
    id: 'es-anlam',
    title: 'Es Anlam',
    category: 'language',
    durationSeconds: 180,
    description: 'Verilen kelimenin es anlamlisini secme oyunu.',
    migrated: true,
  },
  {
    id: 'synonym',
    title: 'Es Anlam',
    category: 'language',
    durationSeconds: 180,
    description: 'Verilen kelimenin es anlamlisini secme oyunu.',
    migrated: true,
  },
  {
    id: 'cumle-ici-es-anlam',
    title: 'Cumle Ici Es Anlam',
    category: 'language',
    durationSeconds: 180,
    description: 'Cumledeki odak kelimenin es anlamlisini baglama gore secme oyunu.',
    migrated: true,
  },
  {
    id: 'sentence-synonym',
    title: 'Cumle Ici Es Anlam',
    category: 'language',
    durationSeconds: 180,
    description: 'Cumledeki odak kelimenin es anlamlisini baglama gore secme oyunu.',
    migrated: true,
  },
  {
    id: 'simge-kodlama',
    title: 'Simge Kodlama',
    category: 'attention',
    durationSeconds: 120,
    description: 'Sayi-sembol kod tablosuna gore hizli secim ve islem hizi oyunu.',
    migrated: true,
  },
  {
    id: 'digit-symbol',
    title: 'Simge Kodlama',
    category: 'attention',
    durationSeconds: 120,
    description: 'Sayi-sembol kod tablosuna gore hizli secim ve islem hizi oyunu.',
    migrated: true,
  },
  {
    id: 'kosullu-yonerge',
    title: 'Kosullu Yonerge',
    category: 'logic',
    durationSeconds: 180,
    description: 'Kosullu ifadeyi degerlendirip dogru nesneyi secme oyunu.',
    migrated: true,
  },
  {
    id: 'conditional-logic',
    title: 'Kosullu Yonerge',
    category: 'logic',
    durationSeconds: 180,
    description: 'Kosullu ifadeyi degerlendirip dogru nesneyi secme oyunu.',
    migrated: true,
  },
  {
    id: 'mantik-bulmacasi',
    title: 'Mantik Bulmacasi',
    category: 'logic',
    durationSeconds: 180,
    description: 'Referans gruplardaki kurala uyan secenegi bulma oyunu.',
    migrated: true,
  },
  {
    id: 'logic-puzzle',
    title: 'Mantik Bulmacasi',
    category: 'logic',
    durationSeconds: 180,
    description: 'Referans gruplardaki kurala uyan secenegi bulma oyunu.',
    migrated: true,
  },
  {
    id: 'sayi-sihirbazi',
    title: 'Sayi Sihirbazi',
    category: 'logic',
    durationSeconds: 180,
    description: 'Toplama, cikarma ve carpma sonucunu hizli bulma oyunu.',
    migrated: true,
  },
  {
    id: 'matematik-grid',
    title: 'Matematik Grid',
    category: 'logic',
    durationSeconds: 180,
    description: '3x3 tabloda eksik hucreleri matematik kuralina gore tamamlama oyunu.',
    migrated: true,
  },
  {
    id: 'gorsel-hafiza',
    title: 'Gorsel Hafiza',
    category: 'memory',
    durationSeconds: 180,
    description: 'Kisa sureli gorsel bellek ve degisim tespiti oyunu.',
    migrated: true,
  },
  {
    id: 'sayisal-hafiza',
    title: 'Sayisal Hafiza',
    category: 'memory',
    durationSeconds: 180,
    description: 'Sayi dizisini hatirlama ve soru cozme odakli calisma oyunu.',
    migrated: true,
  },
  {
    id: 'sayisal-dizi',
    title: 'Sayisal Dizi',
    category: 'logic',
    durationSeconds: 180,
    description: 'Sayi dizisindeki kurali bulup sonraki terimi secme oyunu.',
    migrated: true,
  },
  {
    id: 'number-sequence',
    title: 'Sayisal Dizi',
    category: 'logic',
    durationSeconds: 180,
    description: 'Sayi dizisindeki kurali bulup sonraki terimi secme oyunu.',
    migrated: true,
  },
  {
    id: 'sayisal-sifre',
    title: 'Sayisal Sifre',
    category: 'logic',
    durationSeconds: 180,
    description: 'Sayi iliskilerini okuyup gizli kurali cozme oyunu.',
    migrated: true,
  },
  {
    id: 'number-cipher',
    title: 'Sayisal Sifre',
    category: 'logic',
    durationSeconds: 180,
    description: 'Sayi iliskilerini okuyup gizli kurali cozme oyunu.',
    migrated: true,
  },
  {
    id: 'n-geri-sifresi',
    title: 'N-Geri Sifresi',
    category: 'memory',
    durationSeconds: 180,
    description: 'Sembollerin n-adim onceki haliyle eslesmesini takip etme oyunu.',
    migrated: true,
  },
  {
    id: 'n-back',
    title: 'N-Geri Sifresi',
    category: 'memory',
    durationSeconds: 180,
    description: 'Sembollerin n-adim onceki haliyle eslesmesini takip etme oyunu.',
    migrated: true,
  },
  {
    id: 'kozmik-hafiza',
    title: 'Kozmik Hafiza',
    category: 'memory',
    durationSeconds: 180,
    description: 'Parlayan hucrelerin sirasini normal veya ters modda tekrar etme oyunu.',
    migrated: true,
  },
  {
    id: 'lazer-labirent',
    title: 'Lazer Labirent',
    category: 'logic',
    durationSeconds: 180,
    description: 'Lazer isinini aynalarla takip edip dogru cikisi bulma oyunu.',
    migrated: true,
  },
  {
    id: 'saat-problemi',
    title: 'Saat Problemi',
    category: 'logic',
    durationSeconds: 180,
    description: 'Verilen saat uzerinden ileri-geri dakika hesaplama oyunu.',
    migrated: true,
  },
  {
    id: 'labirent',
    title: 'Labirent',
    category: 'logic',
    durationSeconds: 180,
    description: 'Engeller arasinda dogru rotayi secerek hedefe ulasma oyunu.',
    migrated: true,
  },
  {
    id: 'algisal-hiz',
    title: 'Algisal Hiz',
    category: 'attention',
    durationSeconds: 180,
    description: 'Sayi dizilerinde benzerlik farklilik kararini hizli verme oyunu.',
    migrated: true,
  },
];

export function getRegistryItem(gameId: string): GameRegistryItem | null {
  return GAME_REGISTRY.find((item) => item.id === gameId) ?? null;
}
