import type { CategoryData } from "./types";

export const CATEGORIES: Record<string, CategoryData> = {
  Meyveler: {
    description: "Ağaçlarda ve bitkilerde yetişen tatlı yiyecekler",
    items: [
      { emoji: "🍎", name: "Elma" },
      { emoji: "🍌", name: "Muz" },
      { emoji: "🍇", name: "Üzüm" },
      { emoji: "🍓", name: "Çilek" },
      { emoji: "🍒", name: "Kiraz" },
      { emoji: "🍑", name: "Şeftali" },
      { emoji: "🍍", name: "Ananas" },
      { emoji: "🥝", name: "Kivi" },
      { emoji: "🍉", name: "Karpuz" },
      { emoji: "🍊", name: "Portakal" },
      { emoji: "🍐", name: "Armut" },
      { emoji: "🍋", name: "Limon" },
    ],
  },
  Taşıtlar: {
    description: "İnsanları veya yükleri taşıyan makineler",
    items: [
      { emoji: "🚗", name: "Araba" },
      { emoji: "🚕", name: "Taksi" },
      { emoji: "🚙", name: "Cip" },
      { emoji: "🚌", name: "Otobüs" },
      { emoji: "🏎️", name: "Yarış Arabası" },
      { emoji: "🚓", name: "Polis Arabası" },
      { emoji: "🚑", name: "Ambulans" },
      { emoji: "🚒", name: "İtfaiye" },
      { emoji: "✈️", name: "Uçak" },
      { emoji: "🚁", name: "Helikopter" },
      { emoji: "🚢", name: "Gemi" },
      { emoji: "🚂", name: "Lokomotif" },
    ],
  },
  Hayvanlar: {
    description: "Doğada veya evde yaşayan canlılar",
    items: [
      { emoji: "🐶", name: "Köpek" },
      { emoji: "🐱", name: "Kedi" },
      { emoji: "🐭", name: "Fare" },
      { emoji: "🐹", name: "Hamster" },
      { emoji: "🐰", name: "Tavşan" },
      { emoji: "🦊", name: "Tilki" },
      { emoji: "🐻", name: "Ayı" },
      { emoji: "🐼", name: "Panda" },
      { emoji: "🐨", name: "Koala" },
      { emoji: "🐯", name: "Kaplan" },
      { emoji: "🦁", name: "Aslan" },
      { emoji: "🐮", name: "İnek" },
    ],
  },
  "Spor Topları": {
    description: "Spor ve oyunlarda kullanılan yuvarlak nesneler",
    items: [
      { emoji: "⚽", name: "Futbol Topu" },
      { emoji: "🏀", name: "Basketbol" },
      { emoji: "🏈", name: "Amerikan Futbolu" },
      { emoji: "⚾", name: "Beyzbol" },
      { emoji: "🎾", name: "Tenis Topu" },
      { emoji: "🏐", name: "Voleybol" },
      { emoji: "🏉", name: "Ragbi Topu" },
      { emoji: "🎱", name: "Bilardo" },
      { emoji: "🥎", name: "Softbol" },
      { emoji: "🎳", name: "Bovling" },
    ],
  },
  "Fast Food": {
    description: "Hızlı hazırlanan lezzetli yiyecekler",
    items: [
      { emoji: "🍔", name: "Hamburger" },
      { emoji: "🍟", name: "Patates Kızartması" },
      { emoji: "🍕", name: "Pizza" },
      { emoji: "🌭", name: "Sosisli" },
      { emoji: "🥪", name: "Sandviç" },
      { emoji: "🌮", name: "Taco" },
      { emoji: "🌯", name: "Dürüm" },
      { emoji: "🥙", name: "Lavaş" },
      { emoji: "🍿", name: "Patlamış Mısır" },
      { emoji: "🍩", name: "Donut" },
    ],
  },
  "Hava Durumu": {
    description: "Atmosferin farklı halleri",
    items: [
      { emoji: "☀️", name: "Güneş" },
      { emoji: "🌤️", name: "Güneşli Bulutlu" },
      { emoji: "☁️", name: "Bulut" },
      { emoji: "🌧️", name: "Yağmur" },
      { emoji: "⛈️", name: "Fırtına" },
      { emoji: "🌩️", name: "Şimşek" },
      { emoji: "🌨️", name: "Kar" },
      { emoji: "❄️", name: "Kar Tanesi" },
      { emoji: "🌪️", name: "Kasırga" },
      { emoji: "🌈", name: "Gökkuşağı" },
    ],
  },
  Aletler: {
    description: "Tamir ve inşaat için kullanılan araçlar",
    items: [
      { emoji: "🔨", name: "Çekiç" },
      { emoji: "🪓", name: "Balta" },
      { emoji: "⛏️", name: "Kazma" },
      { emoji: "🛠️", name: "Anahtar" },
      { emoji: "🔧", name: "İngiliz Anahtarı" },
      { emoji: "🪛", name: "Tornavida" },
      { emoji: "📏", name: "Cetvel" },
      { emoji: "🪚", name: "Testere" },
      { emoji: "🧲", name: "Mıknatıs" },
      { emoji: "📐", name: "Gönye" },
    ],
  },
  "Deniz Canlıları": {
    description: "Suda yaşayan hayvanlar",
    items: [
      { emoji: "🐙", name: "Ahtapot" },
      { emoji: "🦑", name: "Kalamar" },
      { emoji: "🦐", name: "Karides" },
      { emoji: "🦞", name: "Istakoz" },
      { emoji: "🦀", name: "Yengeç" },
      { emoji: "🐡", name: "Balon Balığı" },
      { emoji: "🐠", name: "Tropikal Balık" },
      { emoji: "🐟", name: "Balık" },
      { emoji: "🐬", name: "Yunus" },
      { emoji: "🐳", name: "Balina" },
    ],
  },
  Sebzeler: {
    description: "Toprakta yetişen sağlıklı besinler",
    items: [
      { emoji: "🥦", name: "Brokoli" },
      { emoji: "🥬", name: "Marul" },
      { emoji: "🥒", name: "Salatalık" },
      { emoji: "🌽", name: "Mısır" },
      { emoji: "🥕", name: "Havuç" },
      { emoji: "🥔", name: "Patates" },
      { emoji: "🍆", name: "Patlıcan" },
      { emoji: "🧄", name: "Sarımsak" },
      { emoji: "🧅", name: "Soğan" },
      { emoji: "🍄", name: "Mantar" },
    ],
  },
  Giysiler: {
    description: "Giydiğimiz kıyafetler",
    items: [
      { emoji: "👕", name: "Tişört" },
      { emoji: "👖", name: "Pantolon" },
      { emoji: "🧣", name: "Atkı" },
      { emoji: "🧤", name: "Eldiven" },
      { emoji: "🧥", name: "Mont" },
      { emoji: "🧦", name: "Çorap" },
      { emoji: "👗", name: "Elbise" },
      { emoji: "👘", name: "Kimono" },
      { emoji: "🩳", name: "Şort" },
      { emoji: "👔", name: "Kravat" },
    ],
  },
  "Müzik Aletleri": {
    description: "Müzik yapımında kullanılan aletler",
    items: [
      { emoji: "🎹", name: "Piyano" },
      { emoji: "🎸", name: "Gitar" },
      { emoji: "🎺", name: "Trompet" },
      { emoji: "🎻", name: "Keman" },
      { emoji: "🥁", name: "Davul" },
      { emoji: "🪗", name: "Akordeon" },
      { emoji: "🎷", name: "Saksafon" },
      { emoji: "🪘", name: "Darbuka" },
      { emoji: "🎵", name: "Nota" },
      { emoji: "🎶", name: "Müzik" },
    ],
  },
  Çiçekler: {
    description: "Doğanın renkli güzellikleri",
    items: [
      { emoji: "🌸", name: "Kiraz Çiçeği" },
      { emoji: "🌹", name: "Gül" },
      { emoji: "🌻", name: "Ayçiçeği" },
      { emoji: "🌺", name: "Çarkıfelek" },
      { emoji: "🌷", name: "Lale" },
      { emoji: "🌼", name: "Papatya" },
      { emoji: "💐", name: "Buket" },
      { emoji: "🌿", name: "Yaprak" },
      { emoji: "🍀", name: "Yonca" },
      { emoji: "🪻", name: "Sümbül" },
    ],
  },
};
