-- Duyurular tablosu
CREATE TABLE IF NOT EXISTS announcements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    grade TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Ödevler tablosu
CREATE TABLE IF NOT EXISTS assignments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    grade TEXT NOT NULL,
    due_date TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Ödev durumları tablosu
CREATE TABLE IF NOT EXISTS assignment_status (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assignment_id BIGINT REFERENCES assignments(id) ON DELETE CASCADE,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'completed')),
    submitted_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    UNIQUE(assignment_id, user_id)
);

-- Sınıf kayıtları tablosu
CREATE TABLE IF NOT EXISTS classes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    grade TEXT NOT NULL,
    joined_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'inactive')),
    UNIQUE(user_id, grade)
);

-- Sınıf üyelikleri tablosu
CREATE TABLE IF NOT EXISTS class_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    class_id BIGINT REFERENCES classes(id) ON DELETE CASCADE,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    joined_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'inactive')),
    UNIQUE(class_id, user_id)
);

-- RLS politikaları
ALTER TABLE announcements ENABLE ROW LEVEL SECURITY;
ALTER TABLE assignments ENABLE ROW LEVEL SECURITY;
ALTER TABLE assignment_status ENABLE ROW LEVEL SECURITY;
ALTER TABLE classes ENABLE ROW LEVEL SECURITY;
ALTER TABLE class_members ENABLE ROW LEVEL SECURITY;

-- Duyurular için okuma politikası
CREATE POLICY "Duyuruları herkes okuyabilir" ON announcements
    FOR SELECT USING (true);

-- Ödevler için okuma politikası
CREATE POLICY "Ödevleri herkes okuyabilir" ON assignments
    FOR SELECT USING (true);

-- Ödev durumları için politikalar
CREATE POLICY "Kullanıcılar kendi ödev durumlarını görebilir" ON assignment_status
    FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Kullanıcılar kendi ödev durumlarını güncelleyebilir" ON assignment_status
    FOR UPDATE USING (auth.uid() = user_id);

CREATE POLICY "Kullanıcılar kendi ödev durumlarını oluşturabilir" ON assignment_status
    FOR INSERT WITH CHECK (auth.uid() = user_id);

-- Sınıf kayıtları için okuma politikası
CREATE POLICY "Kullanıcılar kendi sınıf kayıtlarını görebilir" ON classes
    FOR SELECT USING (auth.uid() = user_id);

-- Sınıf üyelikleri için okuma politikası
CREATE POLICY "Kullanıcılar kendi sınıf üyeliklerini görebilir" ON class_members
    FOR SELECT USING (auth.uid() = user_id);

-- Tetikleyiciler için fonksiyon
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

-- updated_at kolonunu güncelleyen tetikleyiciler
CREATE TRIGGER update_announcements_updated_at
    BEFORE UPDATE ON announcements
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_assignments_updated_at
    BEFORE UPDATE ON assignments
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_assignment_status_updated_at
    BEFORE UPDATE ON assignment_status
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_classes_updated_at
    BEFORE UPDATE ON classes
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_class_members_updated_at
    BEFORE UPDATE ON class_members
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();
