-- Sınıf öğrencileri tablosu
CREATE TABLE IF NOT EXISTS class_students (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    class_id BIGINT REFERENCES classes(id) ON DELETE CASCADE,
    student_id UUID REFERENCES profiles(id) ON DELETE CASCADE,  -- auth.users yerine profiles
    joined_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    UNIQUE(class_id, student_id)
);

-- RLS politikaları
ALTER TABLE class_students ENABLE ROW LEVEL SECURITY;

-- Okuma politikası
CREATE POLICY "Herkes sınıf öğrencilerini görebilir" ON class_students
    FOR SELECT USING (true);

-- Ekleme politikası
CREATE POLICY "Öğretmenler öğrenci ekleyebilir" ON class_students
    FOR INSERT WITH CHECK (
        EXISTS (
            SELECT 1 FROM classes c
            WHERE c.id = class_id
            AND (c.created_by = auth.uid() OR EXISTS (
                SELECT 1 FROM profiles p
                WHERE p.id = auth.uid()
                AND p.is_admin = true
            ))
        )
    );

-- Silme politikası
CREATE POLICY "Öğretmenler öğrenci silebilir" ON class_students
    FOR DELETE USING (
        EXISTS (
            SELECT 1 FROM classes c
            WHERE c.id = class_id
            AND (c.created_by = auth.uid() OR EXISTS (
                SELECT 1 FROM profiles p
                WHERE p.id = auth.uid()
                AND p.is_admin = true
            ))
        )
    );
