-- Cümle içi eş anlam bulma soruları tablosu
CREATE TABLE IF NOT EXISTS cumle_ici_es_anlam_sorulari (
    id SERIAL PRIMARY KEY,
    cumle TEXT NOT NULL,
    secenek_a TEXT NOT NULL,
    secenek_b TEXT NOT NULL,
    secenek_c TEXT NOT NULL,
    secenek_d TEXT NOT NULL,
    dogru_cevap CHAR(1) NOT NULL CHECK (dogru_cevap IN ('a', 'b', 'c', 'd')),
    dogru_kelime TEXT NOT NULL,
    zorluk TEXT DEFAULT 'orta' CHECK (zorluk IN ('kolay', 'orta', 'zor')),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- RLS politikaları
ALTER TABLE cumle_ici_es_anlam_sorulari ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Herkes cümle içi eş anlam sorularını okuyabilir"
    ON cumle_ici_es_anlam_sorulari FOR SELECT
    USING (true);

-- Zorluk bazlı sorgu için index
CREATE INDEX IF NOT EXISTS idx_cumle_ici_es_anlam_zorluk ON cumle_ici_es_anlam_sorulari(zorluk);
-- 375 cümle içi eş anlam sorusu aktarıldı

INSERT INTO cumle_ici_es_anlam_sorulari (cumle, secenek_a, secenek_b, secenek_c, secenek_d, dogru_cevap, dogru_kelime, zorluk) VALUES
('''Bu melodi içimde farklı hisler oluşturuyor.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'ezgi', 'baş', 'ihracat', 'harp', 'a', 'ezgi', 'orta'),
('''Yüz binlerce öğretmen atama bekliyor.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'asır', 'tayin etmek', 'dilsiz', 'eksik', 'b', 'tayin etmek', 'orta'),
('''Rey atmak için evden çıktık.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'veteriner', 'oy', 'düş', 'kuvvetli', 'b', 'oy', 'orta'),
('''Bu yıl okullarımızdaki derslik sayısını arttırmamız gerekiyor.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'boyut', 'düzyazı', 'sınıf', 'rehber', 'c', 'sınıf', 'orta'),
('''Tercümelerde hata mı var?'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'ana baba', 'bencil', 'rutubet', 'çeviri', 'd', 'çeviri', 'orta'),
('''Duvarı nem, insanı ise gam yıkarmış.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'aza', 'rutubet', 'ziyan', 'hayat', 'b', 'rutubet', 'orta'),
('''Hela kelimesinin ne anlama geldiğini çoğu kişi bilemez.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'adale', 'ortaokul', 'emir', 'tuvalet', 'd', 'tuvalet', 'orta'),
('''Acemi insan öğrenmeye aç insandır?'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'olmamış', 'umut', 'toy', 'eşek', 'c', 'toy', 'orta'),
('''Bu işi sen zor yaparsın.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'taşımacı', 'düzyazı', 'güç', 'kafa', 'c', 'güç', 'orta'),
('''Çabuk olalım aşkım, her şeyi paylaşalım.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'acele', 'hela', 'ehil', 'buhar', 'a', 'acele', 'orta'),
('''Hakimlerin sanıkları bağışlama hakkı yoktur.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'derhal', 'affetmek', 'bilgisiz', 'dönemeç', 'b', 'affetmek', 'orta'),
('''Sana itimat ediyorum ama boşa çıkarmayasın!'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'yetenek', 'halk', 'güven', 'yenik', 'c', 'güven', 'orta'),
('''Sağlık olsun diyerek odadan çıktı.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'sahil', 'gereksiz', 'yobaz', 'sıhhat', 'd', 'sıhhat', 'orta'),
('''İsim ve soy isim lütfen.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'efe', 'iri', 'ad', 'tan', 'c', 'ad', 'orta'),
('''Bu nehir ülkemizin en uzun nehridir.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'oran', 'zevk', 'ırmak', 'sonbahar', 'c', 'ırmak', 'orta'),
('''Sandalyeyi bakmadan oturmaya çalışan kardeşim az kalsın düşüyordu.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'bencil', 'iskemle', 'sır', 'açıklama', 'b', 'iskemle', 'orta'),
('''Dost dediğin arkanı kollar!'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'olay', 'kişi', 'yetenek', 'arkadaş', 'd', 'arkadaş', 'orta'),
('''Mektep görmemiş adamlar bizim yanımıza geliyor.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'okul', 'önlem', 'baş', 'sert', 'a', 'okul', 'orta'),
('''Tarladan bana düşen hisseyi sattım.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'mektep', 'pay', 'medeni', 'Yüzyıl', 'b', 'pay', 'orta'),
('''Bayındırlık hizmetleri gerçekten çok gelişti.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'imar', 'tahsil', 'yobaz', 'biçim', 'a', 'imar', 'orta'),
('''Zarar etmek için beş liraya satman gerek.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'ziyan', 'içten', 'zıt', 'feza', 'a', 'ziyan', 'orta'),
('''Dağın doruk noktasında puslu bir hava var.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'zirve', 'matbaa', 'endüstri', 'çeviri', 'a', 'zirve', 'orta'),
('''Lisanımızda birçok ecnebi kelime bulunmaktadır.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'dil', 'ofis (yazıhane)', 'pis', 'anlam', 'a', 'dil', 'orta'),
('''Hayat bizi farklı alanlara savurdu.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'ana baba', 'ziyan', 'suni', 'yaşam', 'd', 'yaşam', 'orta'),
('''Dilimiz en önemli milli değerlerimiz arasında bulunmaktadır.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'oy', 'berrak', 'küçük', 'lisan', 'd', 'lisan', 'orta'),
('''Matbaada bir aksama olduğu için siparişlerimiz yetişmedi.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'baytar', 'basımevi', 'mümkün', 'dönemeç', 'b', 'basımevi', 'orta'),
('''Ozanlar Anadolu’nun yoğrulmasında çok önemli bir yere sahiptir.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'tamir', 'vaka', 'aniden', 'şair', 'd', 'şair', 'orta'),
('''Zehir gibi sözlerin.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'yasa', 'agu', 'aday', 'tabii', 'b', 'agu', 'orta'),
('''Sonbahar mevsimini çok seviyorum.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'baş', 'Soylu', 'hayat', 'güz', 'd', 'güz', 'orta'),
('''Ödül alan öğrencilerin hepsini sahneye davet ediyoruz.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'mükafat', 'eklem', 'rastlantı', 'seviye', 'a', 'mükafat', 'orta'),
('''Öğrencilik günlerimi çok özlüyorum.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'çalmak', 'tecrübe', 'tuvalet', 'talebe', 'd', 'talebe', 'orta'),
('''Uyarıyı aldım, gelmiyorum.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'istek', 'ikaz', 'cenup', 'görünüm', 'b', 'ikaz', 'orta'),
('''Haysiyetli bir adama herkes güvenir ve herkes iş verir.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'söylev', 'zevk', 'taviz', 'onur', 'd', 'onur', 'orta'),
('''Bazı şekiller insan zekasının gelişmesinde çok etkilidir.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'biçim', 'dargın', 'Hazır', 'uçurum', 'a', 'biçim', 'orta'),
('''İnsanın her konuda düşüncesi olmadığı gibi duygusu da olmayabilir.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'his', 'zıt', 'tek', 'sevinç', 'a', 'his', 'orta'),
('''Kıyılarımızdaki kirliliği görmek istemiyorum.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'güz', 'nesir', 'sahil', 'devir', 'c', 'sahil', 'orta'),
('''Atalarımıza sahip çıkmak okumak ve öğrenmekle olur.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'cet', 'düzyazı', 'doktor', 'nitelik', 'a', 'cet', 'orta'),
('''Hareket eden otobüse binerken ayağı kırılmış.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'eli açık', 'tabiat', 'endüstri', 'devinim', 'd', 'devinim', 'orta'),
('''Bütün çocuklarım benim emrime amade olarak bana hürmet ederler.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'surat', 'Hazır', 'aidat', 'yürek', 'b', 'Hazır', 'orta'),
('''Çok donuk bir renk olması kötü olur.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'ad', 'vaka', 'eser', 'mat', 'd', 'mat', 'orta'),
('''Araçlar aynı anda trafiğe çıktığı için çok kalabalık oldu.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'Vasıta', 'zıt', 'gövde', 'kesin', 'a', 'Vasıta', 'orta'),
('''Olanak sağlansa çocuğum iyi yerlere gelir.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'zevk', 'yeter', 'imkan', 'fert', 'c', 'imkan', 'orta'),
('''Öbür elbiselerimin hepsini yıkamaya vermişler.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'isyan', 'vaka', 'devir', 'diğer', 'd', 'diğer', 'orta'),
('''Üleştiğimiz erikleri hemen bitirdim.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'müessese', 'söylev', 'pay', 'şimendifer', 'c', 'pay', 'orta'),
('''Politikacılar neden yalan söylemek zorunda?'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'siyaset', 'ad', 'tanık', 'taşımacı', 'a', 'siyaset', 'orta'),
('''Eklem ağrılarım beni öldürecek.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'deve', 'şart', 'tanık', 'mafsal', 'd', 'mafsal', 'orta'),
('''O tarafa herhangi bir vasıta olmadığı için gidemedim.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'araç', 'defa', 'şimal', 'sorun', 'a', 'araç', 'orta'),
('''Uygar toplum için iyi eğitim şart.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'cenup', 'fikir', 'medeni', 'aza', 'c', 'medeni', 'orta'),
('''Hatıra para biriktirmekten ne anlarlar!'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'anı', 'komik', 'şimendifer', 'tan', 'a', 'anı', 'orta'),
('''Hemen gel!'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'garp', 'lisan', 'tan', 'derhal', 'd', 'derhal', 'orta'),
('''Gülünç olmak için uğraşma.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'düzyazı', 'para', 'komik', 'mümkün', 'c', 'komik', 'orta'),
('''Cahil cahil konuşma ya!'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'para', 'otluk', 'şüphe', 'bilgisiz', 'd', 'bilgisiz', 'orta'),
('''Vilayete gelen köylü çok yabancılık çekti.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'sözcük', 'affetmek', 'il', 'kimi kez, kimi zaman', 'c', 'il', 'orta'),
('''Son aldığımız market ürünlerinin haricinde başka ne var?'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'neşeli', 'dış', 'güç', 'özlem', 'b', 'dış', 'orta'),
('''Bağnaz insanlar kendilerine ve çevrelerine zarar verir.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'yobaz', 'faiz', 'Yüzyıl', 'kuvvetli', 'a', 'yobaz', 'orta'),
('''Güney illerimiz çok sıcak.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'kimi kez, kimi zaman', 'yas', 'feza', 'cenup', 'd', 'cenup', 'orta'),
('''Uğraştığın şeye bak.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'kuvvetli', 'şehir', 'iş', 'umut', 'c', 'iş', 'orta'),
('''Bedava çay dağıttılar bugün.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'parasız', 'sır', 'hela', 'ofis (yazıhane)', 'a', 'parasız', 'orta'),
('''Kutsal emanetlere sahip çıkalım.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'mukaddes', 'yaratık', 'karşıt', 'güvenlik', 'a', 'mukaddes', 'orta'),
('''Elbise kısa mı biraz!'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'sorun', 'gereksiz', 'yerel', 'giysi', 'd', 'giysi', 'orta'),
('''Tümör ameliyatı iyi geçmiş.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'ur', 'eğer', 'serseri(aylak)', 'dönem', 'a', 'ur', 'orta'),
('''Bu seçime namzet olmak istiyorum'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'aday', 'sıska', 'pay', 'ten', 'a', 'aday', 'orta'),
('''Çantamda sözlük yok.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'şehir', 'parasız', 'para', 'lügat', 'd', 'lügat', 'orta'),
('''Benim düşümde bir bahçeli evde seninle birlikte yaşamak vardı.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'ırak', 'yatak', 'rüya', 'biçim', 'c', 'rüya', 'orta'),
('''Bu yol çok virajlı olduğu için dikkat etmek gerekiyor.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'acele', 'müspet', 'dış', 'dönemeç', 'd', 'dönemeç', 'orta'),
('''Basit ama etkili bir silah yapalım.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'paralel', 'sevinç', 'yalın', 'açık', 'c', 'yalın', 'orta'),
('''Bir bakış attın kalbimi çaldın, alacağın olsun.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'durum', 'arkadaş', 'nazar', 'sonuç', 'c', 'nazar', 'orta'),
('''Son zamanlar müzik dalında çok önemli yapıtlar kulağa hoş geliyor.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'sahte', 'eser', 'müspet', 'zaman', 'b', 'eser', 'orta'),
('''Ufak tefek şeylerle meşgul olma.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'yurt', 'ilave', 'tanık', 'küçük', 'd', 'küçük', 'orta'),
('''Bu numuneden malın ne olduğu anlaşılmıyor.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'al', 'örnek', 'doktor', 'derhal', 'b', 'örnek', 'orta'),
('''Bu konuda birçok unsuru kontrol altında tutmak gerekir.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'öğe', 'ezgi', 'kimi kez, kimi zaman', 'parantez', 'a', 'öğe', 'orta'),
('''Ekonomi iyi giderse maaşlarınıza zam yapacağım.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'iktisat', 'parasız', 'ezgi', 'elbise', 'a', 'iktisat', 'orta'),
('''Kendimde bir sürü olumsuz hisler taşıdığımı sanıyorum.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'yön', 'kaide', 'menfi', 'zirve', 'c', 'menfi', 'orta'),
('''Biricik kızımın doğum gününe katılmak için özel jetimle on saat uçuş yaptım.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'ırmak', 'tek', 'acı', 'mera', 'b', 'tek', 'orta'),
('''Bu otlakta yılda kaç bin hayvan otlanıyor?'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'sahil', 'mera', 'deve', 'emir', 'b', 'mera', 'orta'),
('''Anıtlar, milli ve manevi değerlerimizin nesiller boyu aktarılıp devam etmesinde önemli bir yere sahiptir.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'şark', 'Abide', 'cimri', 'Yüzyıl', 'b', 'Abide', 'orta'),
('''Son gerçekleşen rastlantı herkesi tedirgin etti.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'karabasan', 'akıl', 'buyruk', 'tesadüf', 'd', 'tesadüf', 'orta'),
('''Şark görevi ne zaman belli olacak?'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'güç', 'güldürü', 'sıska', 'doğu', 'd', 'doğu', 'orta'),
('''Nakliyeci sözleştiği paranın da altında işini yapınca çok sevindik.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'taşımacı', 'biçim', 'yıkıntı', 'taraf', 'a', 'taşımacı', 'orta'),
('''İnsan hayatında ayrıcalıklı bir yere sahip olabilir.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'efe', 'imtiyaz', 'veteriner', 'acı', 'b', 'imtiyaz', 'orta'),
('''Kayıp eşyaların satıldığı yere bakmıştım.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'ırak', 'dış', 'yitik', 'ahenk', 'c', 'yitik', 'orta'),
('''Rüştiyeli arkadaşlarımı gördüm bu sabah.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'neden', 'surat', 'diğer', 'ortaokul', 'd', 'ortaokul', 'orta'),
('''Bu dediklerin birçok manaya gelebilir.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'yaratık', 'anlam', 'hak', 'tabiat', 'b', 'anlam', 'orta'),
('''Emniyette olduğuna sevindim.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'güvenlik', 'mamur', 'vaziyet', 'tanık', 'a', 'güvenlik', 'orta'),
('''Son derece katı bir kalbi var.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'sert', 'rağmen', 'kuşak', 'tan', 'a', 'sert', 'orta'),
('''Lamalar tüküren hayvan türleri arasında bulunmaktadır.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'deve', 'zerzele', 'istek', 'şahıs', 'a', 'deve', 'orta'),
('''Kanun düzeni sağlamak içindir.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'yasa', 'duygulu', 'mamur', 'komik', 'a', 'yasa', 'orta'),
('''Bu hastalık o kadar azap veriyor ki ebedi olarak devam edecek zannediyorum.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'cevap', 'ilginç', 'sonsuz', 'iri', 'c', 'sonsuz', 'orta'),
('''Bilinçli bir insan olarak hareket etmek ve tüketimde de bu bilinci sürdürmek önemlidir.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'şuur', 'mesafe', 'önder', 'hayat', 'a', 'şuur', 'orta'),
('''Bugün oruç tuttuğum için başım çok ağrıdı.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'devinim', 'yalın', 'kafa', 'garp', 'c', 'kafa', 'orta'),
('''Mağlup olduğumuz cephelerden askerlerimizi geri çekmek zorunda kaldık.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'aza', 'kalite', 'yenik', 'görev', 'c', 'yenik', 'orta'),
('''Kenara yüz.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'kıyı', 'sır', 'Hediye', 'düzyazı', 'a', 'kıyı', 'orta'),
('''Konukların ne zaman gelecek?'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'gereksiz', 'ahenk', 'misafir', 'tecrübe', 'c', 'misafir', 'orta'),
('''Olmadım bir lahza rahat geçti devranım benim.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'ideal', 'an', 'onur', 'tesadüf', 'b', 'an', 'orta'),
('''Ödün verememek için her işimizi düzgün yapmak zorundayız.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'tan', 'taviz', 'başka', 'şair', 'b', 'taviz', 'orta'),
('''Güz geldi, yapraklar sarardı.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'vaka', 'tümce', 'sonbahar', 'tayin etmek', 'c', 'sonbahar', 'orta'),
('''Ürem konusunda bankalar asla taviz vermiyor.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'lügat', 'hareket', 'faiz', 'matbaa', 'c', 'faiz', 'orta'),
('''Dün tuhaf bir rüya gördüm.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'onur', 'garip', 'tabii', 'uçurum', 'b', 'garip', 'orta'),
('''Kuşku duyuyorsan beni işe alma.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'devinim', 'öfke', 'mahsul', 'şüphe', 'd', 'şüphe', 'orta'),
('''Bilgisiz bir toplum yok olmaya mahkum bir toplumdur.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'parasız', 'mat', 'cahil', 'atama', 'c', 'cahil', 'orta'),
('''Savaşmadan anlaşmaya varılsa, ne güzel olur!'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'akıl', 'rey', 'harp', 'olmamış', 'c', 'harp', 'orta'),
('''Elinizdeki cihazları bırakarak lütfen beni dinleyin.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'aygıt', 'vaka', 'bencil', 'hapishane', 'a', 'aygıt', 'orta'),
('''Arkadaşlar ben devamlı olarak okula gidip geliyorum.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'şair', 'tamir', 'sürekli', 'ihracat', 'c', 'sürekli', 'orta'),
('''Bak tekrar söylüyorum: "Gel!"'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'kaygı', 'yine', 'bütün', 'eli açık', 'b', 'yine', 'orta'),
('''Son dönemeçten dönünce hemen sağa girin ve dükkana gelin.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'viraj', 'diyar', 'imtiyaz', 'armağan', 'a', 'viraj', 'orta'),
('''Her şeye rağmen seninle beraber olmak istiyorum.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'sonsuz', 'karşın', 'tesadüf', 'neden', 'b', 'karşın', 'orta'),
('''Küsmüyüz hayırdır!'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'çalgı', 'parantez', 'devir', 'dargın', 'd', 'dargın', 'orta'),
('''Güçlü insanlar toplumda kendilerini daha iyi ifade ederler.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'cenup', 'kuvvetli', 'sıhhat', 'korkak', 'b', 'kuvvetli', 'orta'),
('''Kırmızı botları kim aldı?'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'giysi', 'kalite', 'sözcük', 'al', 'd', 'al', 'orta'),
('''Pamukkalenin kuzey kapısından girelim.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'düş', 'zevk', 'para', 'şimal', 'd', 'şimal', 'orta'),
('''Maçta ilginç anlar yaşanırken hakem maça ara vermeyi tercih etti.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'zengin', 'zirve', 'enteresan', 'veteriner', 'c', 'enteresan', 'orta'),
('''Rüya görüyorum ama hatırlamıyorum.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'Hediye', 'düş', 'şimendifer', 'ırmak', 'b', 'düş', 'orta'),
('''Düşünce söze düşünce sanırım hedefi buldum.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'dargın', 'mecmua', 'acı', 'fikir', 'd', 'fikir', 'orta'),
('''Öbek öbek karıncalar evin her yanını sarmışlar.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'eli açık', 'bilgisiz', 'grup', 'eser', 'c', 'grup', 'orta'),
('''Gramer hatalarını yok sayamam.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'Abide', 'parantez', 'dilbilgisi', 'fikir', 'c', 'dilbilgisi', 'orta'),
('''Batıda her toplumun kendine özgü bir hayatı vardır ve kimse kimseye karışmaz.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'elbise', 'cevap', 'garp', 'kuvvetli', 'c', 'garp', 'orta'),
('''Depremler son günlerde hızla bir artış gösteriyor.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'zerzele', 'büyük', 'tahsil', 'cemiyet', 'a', 'zerzele', 'orta'),
('''Ulu önderler peşinde gitmekten memnun oluruz.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'millet', 'rüya', 'yüce', 'garip', 'c', 'yüce', 'orta'),
('''Ulus olarak hep birlikte olalım.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'yar', 'hapishane', 'millet', 'taraf', 'c', 'millet', 'orta'),
('''At yolda giderken önüne birdenbire kirpi çıkınca çok irkildi.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'aniden', 'tahsil', 'korkak', 'cet', 'a', 'aniden', 'orta'),
('''Yapay zeka önümüzdeki yıllar adından çok söz ettirecek.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'suni', 'geveze', 'kalite', 'agu', 'a', 'suni', 'orta'),
('''Ülkemiz ekonomik büyüklük olarak dünyada 19. sırada.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'diyar', 'rastlantı', 'yasa', 'ürün', 'a', 'diyar', 'orta'),
('''Anlamlı cümleler kurarak konuşmanızı bekliyorum.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'veteriner', 'tümce', 'parasız', 'açık', 'b', 'tümce', 'orta'),
('''Hudut boyunda elimde silahım, kalbimde sevgimle beklerim seni yar.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'şuur', 'yetenek', 'ofis (yazıhane)', 'sınır', 'd', 'sınır', 'orta'),
('''Aş bilmez iş bilmez bir adam olarak tanınmış.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'siyaset', 'yemek', 'tecrübe', 'bayındır', 'b', 'yemek', 'orta'),
('''Keder dolu yılların ardından bizi mutlu günler bekliyor.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'şehir', 'acı', 'doktor', 'alaka', 'b', 'acı', 'orta'),
('''Oy kullanmak için köyden şehre iki günde geldik.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'yitik', 'diğer', 'eğer', 'rey', 'd', 'rey', 'orta'),
('''Zeybekler diyarı Denizli''dir.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'mukaddes', 'tapınak', 'hiddet', 'efe', 'd', 'efe', 'orta'),
('''Makinenin son devinimi iyice ısınmasına neden oldu.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'hareket', 'Hazır', 'araç', 'eksik', 'a', 'hareket', 'orta'),
('''Asil bir insan olduğunu hemen anladım ve yanına gittim.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'çalgı', 'Soylu', 'yitik', 'açık', 'b', 'Soylu', 'orta'),
('''İmar müdürlüğündeki ihaleye katıldık.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'eser', 'paralel', 'sonuç', 'bayındır', 'd', 'bayındır', 'orta'),
('''Bu caddede açtığımız büroların tamamı kiralıktır ve kiralanmıştır.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'ofis (yazıhane)', 'belge', 'acı', 'sulh', 'a', 'ofis (yazıhane)', 'orta'),
('''Dergi çıkarmak çok maliyetli bir iştir.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'doğu', 'mecmua', 'defa', 'müspet', 'b', 'mecmua', 'orta'),
('''Giysilerimi kim yıkadı?'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'elbise', 'vakit', 'tamir', 'akıl', 'a', 'elbise', 'orta'),
('''Yarın kar yağması olası.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'aza', 'hiddet', 'mümkün', 'alan', 'c', 'mümkün', 'orta'),
('''Hediye almak için dünden beri uğraşıyorum.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'armağan', 'zıt', 'savaş', 'eser', 'a', 'armağan', 'orta'),
('''Menfi hareketleri olan bir çocuk olduğu için pek sevilmez.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'olumsuz', 'iktisat', 'meridyen', 'önlem', 'a', 'olumsuz', 'orta'),
('''Kent içinde ev almayı düşünüyorum.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'yenik', 'besin', 'mera', 'şehir', 'd', 'şehir', 'orta'),
('''Ant içerek bir işe başlamak şeref meselesi olur.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'basit', 'siyah', 'Yemin', 'rey', 'c', 'Yemin', 'orta'),
('''Kocaman sevgisi olan bir dünyada yaşamak istiyorum.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'görünüm', 'sonbahar', 'örnek', 'iri', 'd', 'iri', 'orta'),
('''Süte ek bir de bal getir.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'çalmak', 'ilave', 'çalgı', 'neden', 'b', 'ilave', 'orta'),
('''Bana iki dilim tatlı vermen kafi canım.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'yurt', 'harp', 'şuur', 'yeter', 'd', 'yeter', 'orta'),
('''Ayakyoluna gitmek için özel izin almanıza gerek yok.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'özlem', 'şeref', 'boyut', 'hela(WC)', 'd', 'hela(WC)', 'orta'),
('''Son durumumdaki beğeniler oldukça fazla olduğu için bu durumun hoşuma gitti.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'başşehir', 'his', 'isyan', 'zevk', 'd', 'zevk', 'orta'),
('''Bu olayın düzmece olduğu her halinden anlaşılıyordu.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'sahte', 'Soylu', 'faiz', 'matbaa', 'a', 'sahte', 'orta'),
('''Öğrenim gördüğü okul bu sene depremden yıkılmış.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'başka', 'aygıt', 'ortaokul', 'tahsil', 'd', 'tahsil', 'orta'),
('''Şahit olduğum bir kaza var.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'tanık', 'tapınak', 'uçurum', 'ehil', 'a', 'tanık', 'orta'),
('''Bu cihetle olayları değerlendirdiğimizde herkes haklı gözüküyor.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'aygıt', 'al', 'yön', 'siyah', 'c', 'yön', 'orta'),
('''Ürünleri düzgünce yerleştirsene.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'yel', 'il', 'cahil', 'mahsul', 'd', 'mahsul', 'orta'),
('''Kabus görmekten artık doğru düzgün uyuyamıyorum.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'müspet', 'berrak', 'karabasan', 'unsur', 'c', 'karabasan', 'orta'),
('''Gönül isterdi ki bütün dilekleriniz kabul olsun.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'istek', 'geveze', 'veteriner', 'asır', 'a', 'istek', 'orta'),
('''Anlam dolu hareketler yapman beni tedirgin ediyor.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'belge', 'zaman', 'Mana', 'geveze', 'c', 'Mana', 'orta'),
('''Veterinerde hayvan sevgisi olmalı.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'meşhur', 'gösteriş', 'şüphe', 'baytar', 'd', 'baytar', 'orta'),
('''Yar ucuna geldik ikimizde aaman dikkat...'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'öfke', 'uçurum', 'alan', 'sanayi', 'b', 'uçurum', 'orta'),
('''Her zaman doğal ürünlerle beslenmek gerekir.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'tabii', 'özlem', 'vakit', 'ilgeç', 'a', 'tabii', 'orta'),
('''Ülküm, ülkeye başkan olmak.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'ani', 'ideal', 'sade', 'düş', 'b', 'ideal', 'orta'),
('''Gıda zehirlenmesi sonucu hastaneye kaldırıldı.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'besin', 'an', 'yaratık', 'sonsuz', 'a', 'besin', 'orta'),
('''Öfke dolu açıklamalar yaparak bir yere varamıyoruz.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'hiddet', 'hapishane', 'Ansızın', 'nasihat', 'a', 'hiddet', 'orta'),
('''Yürek her attığında sevgini hissediyorum.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'şüphe', 'korkak', 'kalp', 'karabasan', 'c', 'kalp', 'orta'),
('''Din nasihattir ve nasihate uymak gerekir.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'parantez', 'al', 'vaka', 'öğüt', 'd', 'öğüt', 'orta'),
('''Kamu mallarına zarar verme.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'savaş', 'yalın', 'halk', 'neden', 'c', 'halk', 'orta'),
('''Kirli ayakakbılarla içeri girme demedim mi sana!'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'çalgı', 'pis', 'şair', 'eşek', 'b', 'pis', 'orta'),
('''Uslu insanları herkes sever.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'akıl', 'korkak', 'neden', 'çalmak', 'a', 'akıl', 'orta'),
('''Macera yaşamayı pek sevmediği için evden bile çıkmaz.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'devinim', 'ilave', 'serüven', 'yeter', 'c', 'serüven', 'orta'),
('''Belli bir kapital olmadan düzen oluşturamayız.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'millet', 'Yemin', 'anamal', 'baş', 'c', 'anamal', 'orta'),
('''Uzun yazılarda ayraç kullanılabilir ama kısa yazılarda dipnot tercih etmek daha mantıklıdır.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'parantez', 'kafa', 'şüphe', 'güvenlik', 'a', 'parantez', 'orta'),
('''Kendisi sürekli hayal kurduğu için bazen gerçekleri şaşırıyor.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'düş', 'fert', 'basit', 'işlik', 'a', 'düş', 'orta'),
('''Mafsallarımdaki ağrılar gün geçtikçe artıyordu.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'devir', 'yurt', 'eklem', 'ehil', 'c', 'eklem', 'orta'),
('''İnsanlar tarih boyunca merkeplerden istifade etmişlerdir.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'eli açık', 'lisan', 'eşek', 'siyah', 'c', 'eşek', 'orta'),
('''Zıt anlamlı kelimeleri kim bulmak ister?'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'zeybek', 'karşıt', 'sorun', 'Ansızın', 'b', 'karşıt', 'orta'),
('''Bu düzeyde insanlar birbirlerine selam bile vermezler.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'seviye', 'rağmen', 'mafsal', 'meşhur', 'a', 'seviye', 'orta'),
('''Bozkır bitki örtüsü ülkemizde Anadolu merkezli bölgelerde yayılmış vaziyettedir.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'yapı', 'pis', 'siyaset', 'step', 'd', 'step', 'orta'),
('''İki hamur arasındaki un oranı farkı çok belli oluyor.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'dönemeç', 'nispet', 'şair', 'adale', 'b', 'nispet', 'orta'),
('''Gelmenizden şeref duyarım.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'millet', 'onur', 'imtiyaz', 'genel', 'b', 'onur', 'orta'),
('''Son dizede yer alan özel isimleri inceleyelim.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'bunalım', 'paralel', 'eklem', 'mısra', 'd', 'mısra', 'orta'),
('''Bana nutuk çekecek ola en son kişi sensin.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'hemen', 'yel', 'söylev', 'görünüm', 'c', 'söylev', 'orta'),
('''Kuvvetli olmak için iyi beslenelim.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'enteresan', 'sahte', 'güç', 'meşhur', 'c', 'güç', 'orta'),
('''Her birey sorumluluğunun ve haklarının farkında olmak zorundadır.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'adale', 'harp', 'fert', 'ilgeç', 'c', 'fert', 'orta'),
('''Doktorların çalışma saatleri her zaman tartışılıyor.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'işlik', 'sert', 'unsur', 'hekim', 'd', 'hekim', 'orta'),
('''Saha aaştırmasında petrol bulunamadı.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'alan', 'güven', 'tayin etmek', 'mukaddes', 'a', 'alan', 'orta'),
('''Babandan onay almadan hiçbir şey yapamazsın.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'name', 'tasdik', 'harp', 'acele', 'b', 'tasdik', 'orta'),
('''Kir içinde saçların.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'giysi', 'sert', 'pislik', 'sonuç', 'c', 'pislik', 'orta'),
('''Kanıt mı istiyorsun?'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'delil', 'görünüm', 'yeter', 'siyah', 'a', 'delil', 'orta'),
('''Neticede sen ve ben aynı yurtta kalmaya devam edeceğiz.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'ziyan', 'sonuç', 'al', 'öğe', 'b', 'sonuç', 'orta'),
('''İlgi duyduğum insanlar hep beni yarı yolda bıraktı.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'yalın', 'alaka', 'yar', 'alıcı', 'b', 'alaka', 'orta'),
('''Hasis olan dedem dün bana bisiklet almış. Hayret!'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'suni', 'cimri', 'ahenk', 'Vasıta', 'b', 'cimri', 'orta'),
('''Şafak vakti balığa gideceğiz.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'cet', 'kafa', 'isyan', 'tan', 'd', 'tan', 'orta'),
('''Tuvalet ihtiyacını gider, gidiyoruz.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'hela', 'komik', 'kalp', 'anlam', 'a', 'hela', 'orta'),
('''Nesiller boyu devam eden bir örfümüz vardır.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'kuşak', 'taşımacı', 'vakit', 'mümkün', 'a', 'kuşak', 'orta'),
('''İlave tedbirlerle bu krizden çıkacağız.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'ilgeç', 'elbise', 'ek', 'anamal', 'c', 'ek', 'orta'),
('''Hekimler her zaman en doğru olanı yapmazlar.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'doktor', 'aday', 'tuvalet', 'nasihat', 'a', 'doktor', 'orta'),
('''Mahallemizdeki binalar deprem dolayısıyla tek tek yıkıldı.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'güven', 'yapı', 'sert', 'ur', 'b', 'yapı', 'orta'),
('''Sahil güvenlik, bir gemiyi durdurdu.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'girişken', 'kıyı', 'nasihat', 'tecrübe', 'b', 'kıyı', 'orta'),
('''Bir hafta içinde nakit bulamazsam borçlu olduğum kişilere mahcup olacağım.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'seviye', 'vitrin', 'para', 'armağan', 'c', 'para', 'orta'),
('''Camlarda bir buğulanma olması görüş açımızı iyice düşürüyor.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'millet', 'ehil', 'buhar', 'harp', 'c', 'buhar', 'orta'),
('''Kendi kabiliyetlerimizi ortaya çıkarmak zorundayız.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'deve', 'yetenek', 'toy', 'bencil', 'b', 'yetenek', 'orta'),
('''Emir vermek istemiyorum ama: "Getir şunu."'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'şehir', 'buyruk', 'çeviri', 'Ansızın', 'b', 'buyruk', 'orta'),
('''Kapıyı açar açmaz aniden karşımıza bir ayı çıkmasın mı?'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'yas', 'ahenk', 'yatak', 'Ansızın', 'd', 'Ansızın', 'orta'),
('''En bayağı kıyafetleri yardım diye vermek de neyin nesi oluyor?'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'hücum', 'mümkün', 'adi', 'ideal', 'c', 'adi', 'orta'),
('''Hane halkı sayısı bu evde çok.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'yine', 'ev', 'ad', 'serseri(aylak)', 'b', 'ev', 'orta'),
('''Şahıs şirketi kurmayı planlıyorum.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'kuşak', 'oy', 'uçurum', 'kişi', 'd', 'kişi', 'orta'),
('''Başvuru yaptığım üniversite beni almadı.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'mera', 'müracaat', 'Hazır', 'başka', 'b', 'müracaat', 'orta'),
('''Aza sayısını hangi kanun belirliyor?'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'başka', 'deve', 'yine', 'üye', 'd', 'üye', 'orta'),
('''Egoist insanlardan hep uzak durmuşumdur.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'tür', 'yar', 'bencil', 'dil', 'c', 'bencil', 'orta'),
('''Ödlek insanlar her zaman kararsız kalırlar.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'alaka', 'ortaokul', 'korkak', 'güldürü', 'c', 'korkak', 'orta'),
('''Kırmızı araba mesafeyi çok açmış.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'durum', 'ara', 'sınıf', 'ofis (yazıhane)', 'b', 'ara', 'orta'),
('''Duru sular, durgun sular değildir, durgun sular da azalır gider.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'sonbahar', 'karabasan', 'örnek', 'berrak', 'd', 'berrak', 'orta'),
('''Vakit geldi.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'derhal', 'Soylu', 'zaman', 'baytar', 'c', 'zaman', 'orta'),
('''Günlerdir düzyazı hazırlamaya çalışan öğrenciler, çok zorlanıyor.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'mısra', 'umut', 'nesir', 'görev', 'c', 'nesir', 'orta'),
('''Cılız insanlar dayanıksız ve dirayetsiz insanlar olurlar.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'tahsil', 'sıska', 'yenik', 'özlem', 'b', 'sıska', 'orta'),
('''Tedbir olarak boşaltın burayı.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'yenik', 'mecmua', 'önlem', 'name', 'c', 'önlem', 'orta'),
('''Bu kişiler hakkında bir fikrim yok.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'öğüt', 'şahıs', 'tuvalet', 'tapınak', 'b', 'şahıs', 'orta'),
('''Kas yapmak için ağırlık kaldırıyormuş.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'özlem', 'çeviri', 'adale', 'Hazır', 'c', 'adale', 'orta'),
('''Kısa bir izah verdikten hemen sonra konuya geçti.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'tümce', 'açıklama', 'mümkün', 'genel', 'b', 'açıklama', 'orta'),
('''Adam hastalıktan yatak döşek yatıyordu.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'uyak', 'kız kardeş', 'imtiyaz', 'yatak', 'd', 'yatak', 'orta'),
('''Zaman hızla geçiyor. Sevdiklerine sım sıkı sarıl.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'sıra', 'taraf', 'önder', 'vakit', 'd', 'vakit', 'orta'),
('''Bitkiler havadaki oksijen miktarının belirlenmesinde önemli bir yere sahiptir.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'eşek', 'nispet', 'söz', 'nebat', 'd', 'nebat', 'orta'),
('''Sanayi devrimi ile ekonomimiz şahlanacak.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'mısra', 'karabasan', 'cemiyet', 'endüstri', 'd', 'endüstri', 'orta'),
('''Varlıklı insanlardan olmak isterim.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'yar', 'matbaa', 'zengin', 'çeviri', 'c', 'zengin', 'orta'),
('''Üye olarak ben de varım.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'aza', 'hücum', 'gövde', 'onur', 'a', 'aza', 'orta'),
('''Kafandaki şapka komik oluş.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'step', 'gülünç', 'imtiyaz', 'şeref', 'b', 'gülünç', 'orta'),
('''Sebep ne olursa olsun mutlaka mantıklı bir açıklaması olmalı.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'al', 'yalın', 'tapınak', 'neden', 'd', 'neden', 'orta'),
('''Bana hikaye okuma, Zekaye oku.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'öykü', 'uçurum', 'ek', 'şark', 'a', 'öykü', 'orta'),
('''Ekrem, o işin ustası.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'ilginç', 'garp', 'unsur', 'ehil', 'd', 'ehil', 'orta'),
('''Enkaz altında kalan son yaralı da çıkarıldı.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'sonsuz', 'alan', 'vakit', 'yıkıntı', 'd', 'yıkıntı', 'orta'),
('''Ben konuşurken yüzüme bak!'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'armağan', 'güç', 'cenup', 'surat', 'd', 'surat', 'orta'),
('''Ünlü birini görünce heyecanlanıyorum.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'güç', 'dönemeç', 'ilgeç', 'meşhur', 'd', 'meşhur', 'orta'),
('''Olayların ardı arkası kesilmiyordu.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'yürek', 'vaziyet', 'içten', 'vaka', 'd', 'vaka', 'orta'),
('''Toplum yanlış düşünüyor diye doğruları yapmamazlık etme.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'hareket', 'cemiyet', 'aza', 'yapı', 'b', 'cemiyet', 'orta'),
('''Tüm yolcuların dikkatine, gidiyoruz.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'alan', 'dönem', 'yel', 'bütün', 'd', 'bütün', 'orta'),
('''Laf lafı açtı derken saat çok geç oldu.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'itimat', 'söz', 'ev', 'basit', 'b', 'söz', 'orta'),
('''Koşullar bana göre değil, iyi günler.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'zarar', 'para', 'pis', 'şart', 'd', 'şart', 'orta'),
('''Cömert olmak doğuştan gelen bir özelliktir.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'kalite', 'İfade', 'olumsuz', 'eli açık', 'd', 'eli açık', 'orta'),
('''Bu işin bize çok fazla ziyanı dokunacak.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'zarar', 'mümkün', 'zeybek', 'mamur', 'a', 'zarar', 'orta'),
('''Ümit ederim ki bu sınavı kazanırım.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'aidat', 'umut', 'yar', 'rüya', 'b', 'umut', 'orta'),
('''Camekanlardaki oyuncakları kim alır?'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'sıska', 'vitrin', 'imkan', 'itimat', 'b', 'vitrin', 'orta'),
('''Lüzumsuz işler peşinde koşmamak gerekir.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'surat', 'gereksiz', 'sıra', 'ilgeç', 'b', 'gereksiz', 'orta'),
('''Arkadaşlarımın arasında lafazan olan çok kişi var.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'anı', 'yaşam', 'söz', 'geveze', 'd', 'geveze', 'orta'),
('''Kesin mi kazandığımız?'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'taşımacı', 'armağan', 'belge', 'kati', 'd', 'kati', 'orta'),
('''Deneyim yapmak için bütün öğrencileri okul bahçesine çıkardılar.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'tecrübe', 'yatak', 'sınıf', 'ezgi', 'a', 'tecrübe', 'orta'),
('''Kaç öğeyi sıralamak gerekiyor?'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'Hazır', 'uçurum', 'adale', 'unsur', 'd', 'unsur', 'orta'),
('''Kaliteli mal almak herkesin hakkı.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'nitelik', 'başşehir', 'sahil', 'menfi', 'a', 'nitelik', 'orta'),
('''Başıboş avare öğrenci de istemiyorum.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'şehir', 'delil', 'devinim', 'serseri(aylak)', 'd', 'serseri(aylak)', 'orta'),
('''Mahlukların en şereflisi insan olarak bilinmektedir.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'kati', 'korkak', 'yaratık', 'nebat', 'c', 'yaratık', 'orta'),
('''Sade bir elbise giymiş.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'defa', 'uyak', 'yalın', 'onur', 'c', 'yalın', 'orta'),
('''Buhran dönemlerinde en büyük yardımlar manevi yardımlar olmaktadır.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'cevap', 'bunalım', 'vaka', 'istek', 'b', 'bunalım', 'orta'),
('''Adalet bir ülkenin direğidir.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'müracaat', 'atama', 'neden', 'hak', 'd', 'hak', 'orta'),
('''Kuruluş olarak son derece disiplinli çalışırız.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'araç', 'iktisat', 'meridyen', 'müessese', 'd', 'müessese', 'orta'),
('''Son devrede yaşanan olaylar bütün milletimizi üzmüştür.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'uçurum', 'Yüzyıl', 'dönem', 'hekim', 'c', 'dönem', 'orta'),
('''Kafiyeli şiir yazdım sevdiğime.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'Vasıta', 'uyak', 'Soylu', 'devir', 'b', 'uyak', 'orta'),
('''Kara kalemler geldi.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'nahiye', 'siyah', 'çeviri', 'faiz', 'b', 'siyah', 'orta'),
('''Eğer dürüst bir kılavuz bulursak bu şehri tam anlamıyla gezebiliriz.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'rehber', 'kız kardeş', 'pay', 'mümkün', 'a', 'rehber', 'orta'),
('''Bu manzarayı gerçekten çok sevdim.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'acele', 'görünüm', 'sahil', 'yalın', 'b', 'görünüm', 'orta'),
('''Bu işlere fazla kafa yorarsak hiçbirinin içinden çıkamayız.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'baş', 'Soylu', 'yön', 'kuşak', 'a', 'baş', 'orta'),
('''Efeler diyarı Denizli''ye hoş geldiniz.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'Hediye', 'asır', 'zeybek', 'lisan', 'c', 'zeybek', 'orta'),
('''Dilim lal oldu, gözüm görmez oldu.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'imkan', 'dilsiz', 'karşıt', 'şair', 'b', 'dilsiz', 'orta'),
('''Yüzyıl yaşayan bir akrabam var.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'diyar', 'asır', 'vitrin', 'adale', 'b', 'asır', 'orta'),
('''Mektuplarınızı aldım hepsine cevap yazacağım.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'başşehir', 'anı', 'seviye', 'name', 'd', 'name', 'orta'),
('''Müstakil bir ev alıp yaşamak istiyorum artık.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'kaide', 'bağımsız', 'agu', 'müracaat', 'b', 'bağımsız', 'orta'),
('''Uzak durun benden!'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'al', 'içten', 'ırak', 'sulh', 'c', 'ırak', 'orta'),
('''Enteresan günlerden geçiyoruz.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'sorun', 'hemen', 'zirve', 'ilginç', 'd', 'ilginç', 'orta'),
('''Matem günlerinin ardından mutlu günler de geldi.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'grup', 'onur', 'yas', 'neden', 'c', 'yas', 'orta'),
('''Endişe etme akşam gelirim.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'an', 'talebe', 'sır', 'kaygı', 'd', 'kaygı', 'orta'),
('''Rutubetli ortamda öksürüğüm azıyor.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'nem', 'yüce', 'cemiyet', 'veteriner', 'a', 'nem', 'orta'),
('''Gizli kalması gereken belgeleri kim aldı?'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'defa', 'ek', 'güven', 'sır', 'd', 'sır', 'orta'),
('''Sana çok kolay sorduğumu sen de biliyorsun.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'gösteriş', 'yerel', 'basit', 'cahil', 'c', 'basit', 'orta'),
('''Ordu derhal harekete geçerek savaş alanına geçti.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'giysi', 'mamur', 'doktor', 'hemen', 'd', 'hemen', 'orta'),
('''Aldığım kalemler noksan çıktı.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'ev', 'yurt', 'gerekli', 'eksik', 'd', 'eksik', 'orta'),
('''Hiddetlenme sevgilim.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'mükafat', 'vaziyet', 'mahsul', 'öfke', 'd', 'öfke', 'orta'),
('''Taşındığımız yer bayındır bir yer olmadığı için çok zorluk çekti.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'serüven', 'ilgeç', 'mamur', 'dış', 'c', 'mamur', 'orta'),
('''Nitelik olarak çok verimli ürünler var.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'mahsul', 'an', 'kalite', 'zevk', 'c', 'kalite', 'orta'),
('''Neşe dolu bir hayatın ardından insanlar hiçbir şey götüremezler.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'sevinç', 'siyah', 'millet', 'mat', 'a', 'sevinç', 'orta'),
('''Şayet benimle gelirsen dondurmayı yersin.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'eğer', 'enteresan', 'taviz', 'cenup', 'a', 'eğer', 'orta'),
('''Enlem konusunu hiç anlayamadım.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'kuvvetli', 'paralel', 'düş', 'nadir', 'b', 'paralel', 'orta'),
('''Çayır çimen geze geze çok yorulduk.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'önder', 'durum', 'lisan', 'otluk', 'd', 'otluk', 'orta'),
('''Atak insanlar kendi sorunlarını kendileri halledebilirler.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'yasa', 'hiddet', 'girişken', 'cemiyet', 'c', 'girişken', 'orta'),
('''Bucak bucak gezerek aradığımız adamlar dün karşımıza dikildiler.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'nahiye', 'endüstri', 'komik', 'şüphe', 'a', 'nahiye', 'orta'),
('''Sınıf başkanı seçilmemde bana yardım eden arkadaşlarıma teşekkür ederim.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'misafir', 'yeter', 'yürek', 'reis', 'd', 'reis', 'orta'),
('''Güven duymuyorsan gideyim!'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'eşek', 'mamur', 'itimat', 'yitik', 'c', 'itimat', 'orta'),
('''Vatan sağolsun.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'hiddet', 'yurt', 'oran', 'özen', 'b', 'yurt', 'orta'),
('''Dışsatım gücü yüksek olan ülkeler güçlü ülkelerdir.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'çeviri', 'ihracat', 'Soylu', 'alıcı', 'b', 'ihracat', 'orta'),
('''Bu yazıda anlatım gücü oldukça etkiliydi.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'deve', 'garip', 'mükafat', 'İfade', 'd', 'İfade', 'orta'),
('''Kalp ritmini duydun mu?'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'nebat', 'ilgeç', 'meridyen', 'yürek', 'd', 'yürek', 'orta'),
('''Birden önüme çıkan forsu görünce çok korktum.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'zengin', 'başka', 'ani', 'yapı', 'c', 'ani', 'orta'),
('''Aylak insanlar her zaman boş gezerler.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'müessese', 'karşıt', 'nahiye', 'serseri', 'd', 'serseri', 'orta'),
('''Ham meyveyi koparmışlar dalından.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'olmamış', 'viraj', 'ürün', 'sert', 'a', 'olmamış', 'orta'),
('''Bir dizi civciv, hepsi de sarı sarı.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'çalgı', 'sıra', 'mat', 'siyaset', 'b', 'sıra', 'orta'),
('''Uçurum kenarında neden durursun ki!'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'ehil', 'dil', 'basit', 'yar', 'd', 'yar', 'orta'),
('''Armağan almak için kardeşimle alışverişe çıktık.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'Hediye', 'şüphe', 'eksik', 'ten', 'a', 'Hediye', 'orta'),
('''Edat, bağlaç ve ünlem konuları genelde birlikte işlenir.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'ilgeç', 'rey', 'tahsil', 'grup', 'a', 'ilgeç', 'orta'),
('''Yalın bir dille hikayesini anlattı.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'sade', 'ideal', 'kesin', 'şair', 'a', 'sade', 'orta'),
('''Durumumuz zarar merkezinde olduğu için işlerimizi yavaşlatıyoruz.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'eli açık', 'vaziyet', 'söylev', 'dönem', 'b', 'vaziyet', 'orta'),
('''Endüstri sektöründe çalışmak ister misin?'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'geveze', 'sanayi', 'sıra', 'yar', 'b', 'sanayi', 'orta'),
('''Bazı cinsten olan bitkiler zehirli olabilirler.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'Yemin', 'eğer', 'tür', 'olay', 'c', 'tür', 'orta'),
('''Annen sana yabancı dilde öğüt verdiği zaman anlayabilir misin?'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'zeybek', 'öfke', 'müessese', 'nasihat', 'd', 'nasihat', 'orta'),
('''Saz çalmayı hep istemişimdir.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'matbaa', 'çalgı', 'meridyen', 'Ansızın', 'b', 'çalgı', 'orta'),
('''Dernek ödentilerinizi hemen ödemeniz gerekmektedir.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'aidat', 'olmamış', 'agu', 'sonuç', 'a', 'aidat', 'orta'),
('''Haline bakmadan ğaca çıkmaya çalışıyor.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'dilsiz', 'durum', 'pay', 'mükafat', 'b', 'durum', 'orta'),
('''Doğu kültürü en derin kültürlerden biri olarak bilinmektedir.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'şark', 'olay', 'ev', 'anlam', 'a', 'şark', 'orta'),
('''Okuldan aşı dolayısıyla erkenden çıktık.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'feza', 'nesir', 'yapı', 'mektep', 'd', 'mektep', 'orta'),
('''Yeni bir vaka olmasa bari.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'tabiat', 'görünüm', 'tecrübe', 'olay', 'd', 'olay', 'orta'),
('''Aka kelimesi milletimiz tarafından pek bilinmemektedir.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'büyük', 'karşın', 'akıl', 'halk', 'a', 'büyük', 'orta'),
('''Yandaki iş yerinin kirasını henüz ödemedik.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'ezgi', 'büyük', 'tecrübe', 'taraf', 'd', 'taraf', 'orta'),
('''Onarım yapmamız için mutlaka para toplamamız gerekiyor.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'şimal', 'aniden', 'tamir', 'endüstri', 'c', 'tamir', 'orta'),
('''Asırlar boyu devam eden güçlü ve kuvvetli devletler kurmuşuz.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'diyar', 'nebat', 'eser', 'Yüzyıl', 'd', 'Yüzyıl', 'orta'),
('''Caka satan insanları hiç sevmiyorum.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'şüphe', 'gösteriş', 'müspet', 'sıska', 'b', 'gösteriş', 'orta'),
('''Nakil işlemlerinin yapılması için son iki saat kaldı.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'kuvvetli', 'yel', 'atama', 'olumsuz', 'c', 'atama', 'orta'),
('''Samimi olmak gerekirse, üstündeki elbise hiç yakışmamış.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'müessese', 'İfade', 'isyan', 'içten', 'd', 'içten', 'orta'),
('''Kuş sürüsüne dalan uçak az kalsın düşüyordu.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'rutubet', 'suni', 'adi', 'tayyare', 'd', 'tayyare', 'orta'),
('''Bütün umumi kararların arkasında yönetim kurulu yer alıyor.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'dönem', 'öykü', 'sınıf', 'genel', 'd', 'genel', 'orta'),
('''Kaç kere af diledim senden bilmiyorum!'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'defa', 'başka', 'vaka', 'kaide', 'a', 'defa', 'orta'),
('''Nesirlerde ele alınması gereken konuları sarih bir şekilde yazmış.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'öğüt', 'rastlantı', 'oran', 'düzyazı', 'd', 'düzyazı', 'orta'),
('''30 cm ara koyarak fidan diktik.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'rastlantı', 'imtiyaz', 'mesafe', 'diyar', 'c', 'mesafe', 'orta'),
('''Lider vasıflı insanlar topluma yön veren insanlardır.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'önder', 'şahıs', 'enteresan', 'iskemle', 'a', 'önder', 'orta'),
('''Yaptığımız çalışmalar teknolojide yeni bir çağ açacaktır.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'yas', 'devir', 'ırmak', 'doktor', 'b', 'devir', 'orta'),
('''Her konuda arzulu olmak insanın başına sorunlar açabilir.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'rastlantı', 'ehil', 'İstek', 'viraj', 'c', 'İstek', 'orta'),
('''Müşteri her zaman haklıdır diyen atalarımız değil miydi?'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'alıcı', 'halk', 'devir', 'mısra', 'a', 'alıcı', 'orta'),
('''Mahalli seçimlerin yapılmasına çok az bir süre kaldı.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'olumsuz', 'tayyare', 'serseri(aylak)', 'yerel', 'd', 'yerel', 'orta'),
('''Babamın beden ölçüleri herkesden farklı.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'atama', 'endüstri', 'gövde', 'mamur', 'c', 'gövde', 'orta'),
('''Tren saat beşte kalkacakmış.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'misafir', 'Mana', 'onur', 'şimendifer', 'd', 'şimendifer', 'orta'),
('''Uzaya çıkmak için neler yapılabilir?'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'baytar', 'feza', 'millet', 'derhal', 'b', 'feza', 'orta'),
('''Bize karşı olumlu tavırları her zaman göz doldurdu.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'müspet', 'ara', 'tanık', 'eklem', 'a', 'müspet', 'orta'),
('''Umut fakirin ekmeğidir derler.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'baytar', 'diğer', 'ümit', 'ten', 'c', 'ümit', 'orta'),
('''Başkent Ankara'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'başşehir', 'otluk', 'sır', 'mamur', 'a', 'başşehir', 'orta'),
('''Ebeveyn olmak çok zor.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'yel', 'sır', 'ana baba', 'elbise', 'c', 'ana baba', 'orta'),
('''Benim bütün bacılarım okul okumuş kimselerdir.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'dönemeç', 'şark', 'seviye', 'kız kardeş', 'd', 'kız kardeş', 'orta'),
('''Sizin buyruklarını yerine getirmek için günlerce çalışıyoruz.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'itimat', 'uyak', 'işlik', 'emir', 'd', 'emir', 'orta'),
('''Harp gazisi dedem dün vefat etti.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'şuur', 'delil', 'savaş', 'eşek', 'c', 'savaş', 'orta'),
('''Bu tarihi olayın vesikalarını arşivden çıkarmak çok zor oldu.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'tapınak', 'belge', 'anamal', 'defa', 'b', 'belge', 'orta'),
('''Son günlerde atölyemizde çıkan sorunlar işimizi aksattı.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'üye', 'işlik', 'pay', 'iri', 'b', 'işlik', 'orta'),
('''Yanıt bekliyorum. Neden geç kaldın?'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'enteresan', 'cevap', 'kıyı', 'serseri(aylak)', 'b', 'cevap', 'orta'),
('''Karşıt görüşlü çok arkadaşım var.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'şeref', 'müessese', 'Mana', 'zıt', 'd', 'zıt', 'orta'),
('''Öğrenciler yemekhaneden ekmek aşırmışlar.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'uyak', 'viraj', 'şuur', 'çalmak', 'd', 'çalmak', 'orta'),
('''Kurallara uymak her zaman hayat kurtarır.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'enteresan', 'sevinç', 'hela(WC)', 'kaide', 'd', 'kaide', 'orta'),
('''Anlamlı cümleler kurarak konuşmanızı bekliyorum.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'meridyen', 'sade', 'tümce', 'sıska', 'c', 'tümce', 'orta'),
('''Ender bulunan taşlardan biridir.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'pis', 'hak', 'uçurum', 'nadir', 'd', 'nadir', 'orta'),
('''Komedi filmlerinde nedense gülmüyorum.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'anamal', 'güldürü', 'boyut', 'güz', 'b', 'güldürü', 'orta'),
('''Lüzumlu evraklar dosyası yapmak gerekiyor.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'tanık', 'ara', 'taraf', 'gerekli', 'd', 'gerekli', 'orta'),
('''Belediye hizmetlerinden anlaşıldığı üzere vaziyet gerçekten çok kötü olabilir.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'hela(WC)', 'nebat', 'zarar', 'durum', 'd', 'durum', 'orta'),
('''Barış içinde yaşamak neden bu kadar zor?'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'sulh', 'yar', 'ezgi', 'sahil', 'a', 'sulh', 'orta'),
('''Uyum programını başarıyla geçtim.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'ahenk', 'Ansızın', 'Yemin', 'kalite', 'a', 'ahenk', 'orta'),
('''Entarisi hangi renk bilemedim!'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'paralel', 'vitrin', 'giysi', 'İfade', 'c', 'giysi', 'orta'),
('''Bazen canım ders çalışmak istemiyor.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'efe', 'kimi kez, kimi zaman', 'sorun', 'ırmak', 'b', 'kimi kez, kimi zaman', 'orta'),
('''İtina ile halı dokumaya devam ediyor.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'yel', 'gerekli', 'gösteriş', 'özen', 'd', 'özen', 'orta'),
('''Basımevi olmadan kitap bastırıyorum.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'matbaa', 'harp', 'besin', 'umut', 'a', 'matbaa', 'orta'),
('''Tesadüf eseri buraya gelmiş.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'rastlantı', 'yitik', 'istek', 'dargın', 'a', 'rastlantı', 'orta'),
('''Vazife düşerse seve seve yaparım.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'bağımsız', 'mektep', 'görev', 'olay', 'c', 'görev', 'orta'),
('''Mahpushane damlarında öğüt veren çok olur.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'lügat', 'ev', 'hapishane', 'baytar', 'c', 'hapishane', 'orta'),
('''Her konuda hassas olan bir insan olduğu için onu idare etmek çok zor.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'tan', 'duygulu', 'fert', 'kafa', 'b', 'duygulu', 'orta'),
('''Doğa canlılarla barışık bir düzen içindedir.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'matbaa', 'tabiat', 'nispet', 'karşın', 'b', 'tabiat', 'orta'),
('''Mahsullerimizin en iyi şekilde yetişmesi için yatırım yapıyoruz.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'başşehir', 'olumsuz', 'ürün', 'buhar', 'c', 'ürün', 'orta'),
('''En iyi saldırı, savunmadır.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'tayyare', 'Soylu', 'hücum', 'nesir', 'c', 'hücum', 'orta'),
('''Hasret duyduğum tek dayım var.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'sınıf', 'basımevi', 'şuur', 'özlem', 'd', 'özlem', 'orta'),
('''Küme olmuş bulutlar, ağlamak üzere.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'şimendifer', 'grup', 'Yüzyıl', 'mecmua', 'b', 'grup', 'orta'),
('''Problem varsa çözeriz.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'özlem', 'şark', 'hareket', 'sorun', 'd', 'sorun', 'orta'),
('''Rüzgar hangi yönden esiyor?'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'rehber', 'mükafat', 'yel', 'sıska', 'c', 'yel', 'orta'),
('''Baytar olmak için uzun yıllar fakültede okumak ve tecrübe etmek gerekir.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'tabiat', 'garp', 'yön', 'veteriner', 'd', 'veteriner', 'orta'),
('''Yatağın ebatları hakkında bilgi verilmedi.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'açık', 'eli açık', 'boyut', 'kuvvetli', 'c', 'boyut', 'orta'),
('''Deri sağlığı için güneş ışınları çok yararlıdır.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'mamur', 'geveze', 'ten', 'sade', 'c', 'ten', 'orta'),
('''Kelime oyunu oynar mısın?'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'sözcük', 'an', 'taşımacı', 'sonuç', 'a', 'sözcük', 'orta'),
('''Seni aleni bir şekilde uyarıyorum bir daha yapma.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'pabuç', 'açık', 'ümit', 'isyan', 'b', 'açık', 'orta'),
('''Benim maaşıma nispetle senin maaşın oldukça yüksek.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'umut', 'oran', 'ortaokul', 'pislik', 'b', 'oran', 'orta'),
('''Hür şehrin esir mabedi olan yapılar göze çarpıyor.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'gösteriş', 'tapınak', 'tuvalet', 'fert', 'b', 'tapınak', 'orta'),
('''Kati ve son kararımdır.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'rastlantı', 'kesin', 'kimi kez, kimi zaman', 'siyah', 'b', 'kesin', 'orta'),
('''Sınavımız olmasına karşın hala oyun oynamaya devam ediyorlar.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'rağmen', 'görev', 'gösteriş', 'lügat', 'a', 'rağmen', 'orta'),
('''Vücut ısısı çok yüksek.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'ilginç', 'buyruk', 'gövde', 'alıcı', 'c', 'gövde', 'orta'),
('''Başkaldırı olan ülkelerde ekonomik buhran olur.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'devir', 'kaygı', 'isyan', 'komik', 'c', 'isyan', 'orta'),
('''Şenlikli bir düğündü.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'mektep', 'ek', 'yatak', 'neşeli', 'd', 'neşeli', 'orta'),
('''Konut alımında yılın en düşük seviyesini gördük'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'ev', 'hak', 'güldürü', 'hemen', 'a', 'ev', 'orta'),
('''Diğer elbiselerimin hepsini yıkamaya vermişler.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'başka', 'ziyan', 'olay', 'halk', 'a', 'başka', 'orta'),
('''Boylamlar dünyada coğrafik konum ve matematik konumun hesaplanmasında önemli bir etkendir.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'Soylu', 'meridyen', 'zirve', 'eklem', 'b', 'meridyen', 'orta'),
('''Ayakkabı almak için 10 dakika çalıştım.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'bencil', 'rağmen', 'nebat', 'pabuç', 'd', 'pabuç', 'orta'),
('''Nefes alıp veren toprak canlılık saçıyor.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'kalp', 'tayin etmek', 'unsur', 'soluk', 'd', 'soluk', 'orta'),
('''Ömür dediğin zamanın sana dayattığı sınırdır.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'hayat', 'vakit', 'çalgı', 'ehil', 'a', 'hayat', 'orta'),
('''Onur sahibi insanlar gerçekten saygıyı hak ederler.'' cümlesindeki bir kelimenin yerine kullanılabilecek eş anlamlı kelime aşağıdakilerden hangisidir?', 'rağmen', 'güven', 'şeref', 'ara', 'c', 'şeref', 'orta');
